name: ci
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: debian, os_rel: buster, image_owner: , package_type: deb}
          - {os: debian, os_rel: buster, image_owner: i386/, package_type: deb}
          - {os: ubuntu, os_rel: bionic, image_owner: , package_type: deb}
          - {os: ubuntu, os_rel: eoan, image_owner: , package_type: deb}
          - {os: raspbian, os_rel: buster, image_owner: igagis/, package_type: deb}
    container: ${{ matrix.image_owner }}${{ matrix.os }}:${{ matrix.os_rel }}
    steps:
      - name: git clone
        uses: actions/checkout@main
      - name: add igagis deb repo
        uses: myci-actions/add-deb-repo@2
        with:
          repo: deb http://dl.bintray.com/igagis/debian buster main
          repo-name: igagis
          keys: 379CE192D401AB61
      - name: install ci tools
        run: apt install --assume-yes devscripts equivs myci
      - name: prepare debian package
        run: myci-deb-prepare.sh
      - name: install deps
        run: myci-deb-install-build-deps.sh
      - name: build
        run: autojobs=true dpkg-buildpackage -us -uc
  macosx:
    runs-on: macos-latest
    steps:
    - name: git clone
      uses: actions/checkout@main
    - name: add igagis tap
      run: brew tap igagis/tap && brew update
    - name: install ci tools
      run: brew install myci
    - name: install deps
      run: myci-brew-install.sh `myci-list-deps-homebrew.sh`
    - name: build
      run: make autojobs=true
    - name: test
      run: make test autojobs=true
