name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: git clone
        uses: actions/checkout@main
      - name: install deps
        run: apt update && apt install --assume-yes make
      - name: make
        run: make autojobs=true
  
