name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: git clone
        uses: actions/checkout@main
      - name: add igagis deb repo
        uses: myci-actions/add-deb-repo@2
        with:
          repo: deb http://dl.bintray.com/igagis/debian buster main
          repo-name: igagis
          keys: 379CE192D401AB61
      - name: install myci
        run: apt install myci
      - name: prepare debian package
        run: myci-deb-prepare.sh
      - name: install deps
        run: myci-deb-install-build-deps.sh
      - name: build package
        run: autojobs=true dpkg-buildpackage -us -uc
